# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Devin Moreland
tagline:          'Data Portfolio'
description:      '<img src="images/IMG-20230324-WA0003.jpg" alt="Devin Moreland"> Data Professional with focus on analyics, machine learning, anomoly detection, and software engineering.'
url:              https://devinmoreland.github.io
baseurl:          /

author:
  name:           'Devin Moreland'
  url:            https://devinmoreland.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
