# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            <font size="15">Devin Moreland</font>
tagline:          'Data Portfolio'
description:      '<u>Data Professional</u> with focus on <b>data science</b>, <b>machine learning</b>, <b>statistics</b>, and <b>software engineering</b>.'
url:              
baseurl:          /

author:
  name:           'Devin Moreland'
  url:            https://devinmoreland.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
