# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Devin Moreland
tagline:          'Data Portfolio'
description:      'Data Professional with focus on analyics, machine learning, anomoly detection, and software engineering.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

